###################################################################
# Logging related settings
# for Twister2 workers
###################################################################

# logging level: FINEST, FINER, FINE, CONFIG, INFO, WARNING, SEVERE
# default value is INFO
twister2.logging.level: "INFO"

# Do workers request persistent logging? it could be true or false
# default value is false
persistent.logging.requested: true

# whether System.out and System.err should be redircted to log files
# When System.out and System.err are redirected to log file,
# All messages are only saved in log files. Only a few intial messages are shown on Dashboard.
# Otherwise, Dashboard has the complete messages,
# log files has the log messages except System.out and System.err.
twister2.logging.redirect.sysouterr: true

# The maximum log file size in MB
twister2.logging.max.file.size.mb: 100

# The maximum number of log files for each worker
twister2.logging.maximum.files: 5